services:
  - type: web
    name: QuanLyDiemSV
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile

    envVars:
      - key: APP_ENV
        value: "production"
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: "https://quanlydiemsv.onrender.com"

      # Database config (tùy chỉnh lại cho đúng thông tin DB của bạn)
      - key: DB_CONNECTION
        value: "mysql"
      - key: DB_HOST
        value: "your-db-host"
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        value: "your-db-name"
      - key: DB_USERNAME
        value: "your-db-user"
      - key: DB_PASSWORD
        value: "your-db-pass"

    autoDeploy: true
